<h1>Python: without numpy or sklearn </h1>

<h3> Q1: Given two matrices please print the product of those two matrices </h3>
<pre>

Ex 1: A   = [[1 3 4]
             [2 5 7]
             [5 9 6]]
      B   = [[1 0 0]
             [0 1 0]
             [0 0 1]]
      A*B = [[1 3 4]
             [2 5 7]
             [5 9 6]]

     
Ex 2: A   = [[1 2]
             [3 4]]
      B   = [[1 2 3 4 5]
             [5 6 7 8 9]]
      A*B = [[11 14 17 20 23]
             [23 30 36 42 51]]
             
Ex 3: A   = [[1 2]
             [3 4]]
      B   = [[1 4]
             [5 6]
             [7 8]
             [9 6]]
      A*B =Not possible
</pre>

In [66]:
# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input examples


A   = [[1,2],
       [3,4]]
B   = [[1,2,3,4,5],
       [5,6,7,8,9]]

# you can free to change all these codes/structure
# here A and B are list of lists
def matrix_mul(A, B):
    # write your code
    if len(A[0]) != len(B):
        return "Not possible"
    result = [[sum(a*b for a,b in zip(row,col)) for col in zip(*B)] for row in A]
    return result
    
print(matrix_mul(A, B))

[[11, 14, 17, 20, 23], [23, 30, 37, 44, 51]]


<h3> Q2: Select a number randomly with probability proportional to its magnitude from the given array of n elements</h3>

consider an experiment, selecting an element from the list A randomly with probability proportional to its magnitude.
assume we are doing the same experiment for 100 times with replacement, in each experiment you will print a number that is selected randomly from A.

<pre>
Ex 1: A = [0 5 27 6 13 28 100 45 10 79]
let f(x) denote the number of times x getting selected in 100 experiments.
f(100) > f(79) > f(45) > f(28) > f(27) > f(13) > f(10) > f(6) > f(5) > f(0)
</pre>

In [67]:
from random import uniform
import random
# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input examples

#Reference: https://stackoverflow.com/questions/57892112 - 'Last Solution'

# you can free to change all these codes/structure
def pick_a_number_from_list(A):
    # your code here for picking an element from with the probability propotional to its magnitude
    weights=[]
    for i in A:
        weights.append(i/sum(A))
        
    rndm_num = random.choices(A,weights,k=1)    
    
    return rndm_num

A = [0,5,27,6,13,28,100,45,10,79]  

def sampling_based_on_magnitued():
    for i in range(1,100):
        number = pick_a_number_from_list(A)
        print(number)

sampling_based_on_magnitued()

[79]
[79]
[100]
[45]
[100]
[45]
[10]
[79]
[79]
[28]
[100]
[27]
[100]
[28]
[100]
[100]
[27]
[79]
[100]
[100]
[79]
[45]
[100]
[100]
[13]
[45]
[79]
[100]
[100]
[100]
[28]
[27]
[28]
[100]
[10]
[79]
[27]
[100]
[100]
[27]
[13]
[100]
[100]
[13]
[100]
[79]
[100]
[13]
[100]
[100]
[10]
[100]
[27]
[100]
[100]
[100]
[13]
[28]
[100]
[45]
[100]
[79]
[79]
[100]
[79]
[79]
[27]
[79]
[79]
[28]
[45]
[100]
[79]
[13]
[100]
[45]
[79]
[79]
[45]
[100]
[45]
[45]
[100]
[79]
[100]
[79]
[100]
[100]
[13]
[13]
[100]
[10]
[100]
[100]
[100]
[28]
[45]
[100]
[27]


<h3> Q3: Replace the digits in the string with #</h3>

consider a string that will have digits in that, we need to remove all the not digits and replace the digits with #
<pre>
Ex 1: A = 234                Output: ###
Ex 2: A = a2b3c4             Output: ###
Ex 3: A = abc                Output:   (empty string)
Ex 5: A = #2a$#b%c%561#      Output: ####
</pre>

In [68]:
import re
# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input examples

# you can free to change all these codes/structure
# String: it will be the input to your program
def replace_digits(String):
    # write your code
    String = re.sub("[^0-9]","",str(String))
    String = re.sub('\d','#',String)
    return String # modified string which is after replacing the # with digits

print(replace_digits('234'))
print(replace_digits('a2b3c4'))
print(replace_digits('abc'))
print(replace_digits('#2a$#b%c%561#'))

###
###

####


<h3> Q4: Students marks dashboard</h3>

consider the marks list of class students given two lists <br>
Students = ['student1','student2','student3','student4','student5','student6','student7','student8','student9','student10'] <br>
Marks = [45, 78, 12, 14, 48, 43, 45, 98, 35, 80] <br>
from the above two lists the Student[0] got Marks[0],  Student[1] got Marks[1] and so on <br><br>
your task is to print the name of students
<strong>a. Who got top 5 ranks, in the descending order of marks</strong> <br>
<strong>b. Who got least 5 ranks, in the increasing order of marks</strong><br>
<strong>d. Who got marks between  &gt;25th percentile &lt;75th percentile, in the increasing order of marks</strong>

<pre>
Ex 1: 
Students=['student1','student2','student3','student4','student5','student6','student7','student8','student9','student10'] 
Marks = [45, 78, 12, 14, 48, 43, 47, 98, 35, 80]
a. 
student8  98
student10 80
student2  78
student5  48
student7  47
b.
student3 12
student4 14
student9 35
student6 43
student1 45
c.
student9 35
student6 43
student1 45
student7 47
student5 48
</pre>

In [8]:
# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input examples

# you can free to change all these codes/structure
students=['student1','student2','student3','student4','student5','student6','student7','student8','student9','student10'] 
marks = [45, 78, 12, 14, 48, 43, 47, 98, 35, 80]
def display_dash_board(students, marks):

    dic = dict(zip(students,marks))

    # write code for computing top top 5 students
    print("a.")
    top_5_students = (sorted(dic.values())[5:])[::-1]
    for m in top_5_students:
        print(list(dic.keys())[list(dic.values()).index(m)],m)
    
    print("\n")
    
    # write code for computing top least 5 students
    print("b.")
    least_5_students = (sorted(dic.values())[:5])
    for m in least_5_students:
        print(list(dic.keys())[list(dic.values()).index(m)], m )
    
    print("\n")
    
    # write code for computing top least 5 students
    # Calculating the 25th and 75th percentile
    diff = max(marks) - min(marks)
    tile_25 = diff*0.25
    tile_75 = diff*0.75
    
    print("c.")
    for m in dic.values():
        if ( m <= tile_75 and m >= tile_25 ):
            print(list(dic.keys())[list(dic.values()).index(m)],m)
            
        else:
            pass
    
    
    #return top_5_students, least_5_students, students_within_25_and_75

display_dash_board(students, marks)
#print(# those values)

a.
student8 98
student10 80
student2 78
student5 48
student7 47


b.
student3 12
student4 14
student9 35
student6 43
student1 45


c.
student1 45
student5 48
student6 43
student7 47
student9 35


<h3> Q5: Find the closest points</h3>

consider you have given n data points in the form of list of tuples like S=[(x1,y1),(x2,y2),(x3,y3),(x4,y4),(x5,y5),..,(xn,yn)] and a point P=(p,q) <br> your task is to find 5 closest points(based on cosine distance) in S from P
<br>cosine distance between two points (x,y) and (p,q) is defind as $cos^{-1}(\frac{(x\cdot p+y\cdot q)}{\sqrt(x^2+y^2)\cdot\sqrt(p^2+q^2)})$
<pre>
Ex:

S= [(1,2),(3,4),(-1,1),(6,-7),(0, 6),(-5,-8),(-1,-1)(6,0),(1,-1)]
P= (3,-4)
<img src='https://i.imgur.com/vIFPOcG.jpg', width=300>
Output:
(6,-7)
(1,-1)
(6,0)
(-5,-8)
(-1,-1)
</pre>

In [70]:
import math

# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input examples
# you can free to change all these codes/structure


# here S is list of tuples and P is a tuple ot len=2
def closest_points_to_p(S, P):
    # write your code here
    distance = {}
    for i in range(len(S)):
        d = math.acos(((S[i][0]*P[0])+(S[i][1]*P[1]))/((math.sqrt((S[i][0]**2)+(S[i][1]**2))) *(math.sqrt((P[0]**2)+(P[1]**2)))))
        distance[S[i]] = d

    dis = sorted(distance.values())[:5]
    for m in dis:
        print(list(distance.keys())[list(distance.values()).index(m)])
    #return closest_points_to_p  # its list of tuples


S= [(1,2), (3,4),(-1,1),(6,-7),(0,6),(-5,-8),(-1,-1),(6,0),(1,-1)]
P= (3,-4)
points = closest_points_to_p(S, P)
print() #print the returned values

(6, -7)
(1, -1)
(6, 0)
(-5, -8)
(-1, -1)



<h3> Q6: Find Which line separates oranges and apples</h3>
consider you have given two set of data points in the form of list of tuples like 
<pre>
Red =[(R11,R12),(R21,R22),(R31,R32),(R41,R42),(R51,R52),..,(Rn1,Rn2)]
Blue=[(B11,B12),(B21,B22),(B31,B32),(B41,B42),(B51,B52),..,(Bm1,Bm2)]
</pre>
and set of line equations(in the string formate, i.e list of strings)
<pre>
Lines = [a1x+b1y+c1,a2x+b2y+c2,a3x+b3y+c3,a4x+b4y+c4,..,K lines]
Note: you need to string parsing here and get the coefficients of x,y and intercept
</pre>
your task is to for each line that is given print "YES"/"NO", you will print yes, if all the red points are one side of the line and blue points are other side of the line, otherwise no
<pre>
Ex:
Red= [(1,1),(2,1),(4,2),(2,4), (-1,4)]
Blue= [(-2,-1),(-1,-2),(-3,-2),(-3,-1),(1,-3)]
Lines=["1x+1y+0","1x-1y+0","1x+0y-3","0x+1y-0.5"]
<img src='https://i.imgur.com/DoQf7mE.jpg' width=400>
Output:
YES
NO
NO
YES
</pre>

In [71]:
import math
# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input strings


# you can free to change all these codes/structure
def i_am_the_one(red,blue,line):

    # Reference: Reference: https://stackoverflow.com/questions/57188227/to-find-whether-a-given-line-equation-is-able-to-separate-the-two-lists-of-poi

    # your code
    a, b, c = [float(coef.strip()) for coef in re.split('x|y', line)]
    
    string_red = ""
    for i in red:
        if a*i[0]+b*i[1]+c<0:
            break
        else:
            string_red += "1"

    string_blue = ""     
    for i in blue:
        if a*i[0]+b*i[1]+c>0:
            break
        else:
            string_blue += "1"
        
    if len(string_red) == len(string_blue):
        return "YES"
    else:
        return "NO"

Red= [(1,1),(2,1),(4,2),(2,4), (-1,4)]
Blue= [(-2,-1),(-1,-2),(-3,-2),(-3,-1),(1,-3)]
Lines=["1x+1y+0","1x-1y+0","1x+0y-3","0x+1y-0.5"]

for i in Lines:
    yes_or_no = i_am_the_one(Red, Blue, i)
    print(yes_or_no) # the returned value

YES
NO
NO
YES


<h3> Q7: Filling the missing values in the specified formate</h3>
You will be given a string with digits and '\_'(missing value) symbols you have to replace the '\_' symbols as explained 
<pre>
Ex 1: _, _, _, 24 ==> 24/4, 24/4, 24/4, 24/4 i.e we. have distributed the 24 equally to all 4 places <br>
Ex 2: 40, _, _, _, 60 ==> (60+40)/5,(60+40)/5,(60+40)/5,(60+40)/5,(60+40)/5 ==> 20, 20, 20, 20, 20 i.e. the sum of (60+40) is distributed qually to all 5 places<br>
Ex 3: 80, _, _, _, _  ==> 80/5,80/5,80/5,80/5,80/5 ==> 16, 16, 16, 16, 16 i.e. the 80 is distributed qually to all 5 missing values that are right to it<br>
Ex 4: _, _, 30, _, _, _, 50, _, _  
==> we will fill the missing values from left to right 
    a. first we will distribute the 30 to left two missing values (10, 10, 10, _, _, _, 50, _, _)
    b. now distribute the sum (10+50) missing values in between (10, 10, 12, 12, 12, 12, 12, _, _) 
    c. now we will distribute 12 to right side missing values (10, 10, 12, 12, 12, 12, 4, 4, 4)
</pre>
for a given string with comma seprate values, which will have both missing values numbers like ex: "_, _, x, _, _, _"
you need fill the missing values

Q: your program reads a string like ex: "_, _, x, _, _, _" and returns the filled sequence

Ex: 
<pre>
Input1: "_,_,_,24"
Output1: 6,6,6,6

Input2: "40,_,_,_,60"
Output2: 20,20,20,20,20

Input3: "80,_,_,_,_"
Output3: 16,16,16,16,16

Input4: "_,_,30,_,_,_,50,_,_"
Output4: 10,10,12,12,12,12,4,4,4
</pre>



In [72]:
# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input strings


# you can free to change all these codes/structure
def curve_smoothing(string):
    # your code
    a = string.split(',')
    count = 0
    m = 0

    # left blanks
    for i in range(len(a)):
        if a[i] == '_':
          # find number of blanks to the left of a number
            count = count + 1  
        else:
            for j in range(i + 1):
                # if there are n blanks to the left of the number speard the number equal over n+1 spaces
                a[j] = int((float(a[i]) / (count + 1)))
            m = i
            value = float(a[i])
            break

    # middle blanks
    d = 1
    flag = 0
    for k in range(m + 1, len(a)):
        if a[k] != '_':
            d = (k + 1 - m)
            flag = k
            break
    f_value = float(a[flag])
    for p in range(m, flag + 1):
        a[p] = int((value + f_value) / d)

    # right blanks
    last_value = float(a[flag])
    for q in range(flag, len(a)):
        a[q] = int(last_value / (len(a) - flag))

    return a

S=  "_,_,30,_,_,_,50,_,_"
smoothed_values= curve_smoothing(S)
print(smoothed_values)

[10, 10, 12, 12, 12, 12, 4, 4, 4]


<h3> Q8: Filling the missing values in the specified formate</h3>
You will be given a list of lists, each sublist will be of length 2 i.e. [[x,y],[p,q],[l,m]..[r,s]]
consider its like a martrix of n rows and two columns
1. the first column F will contain only 5 uniques values (F1, F2, F3, F4, F5)
2. the second column S will contain only 3 uniques values (S1, S2, S3)
<pre>
your task is to find
a. Probability of P(F=F1|S==S1), P(F=F1|S==S2), P(F=F1|S==S3)
b. Probability of P(F=F2|S==S1), P(F=F2|S==S2), P(F=F2|S==S3)
c. Probability of P(F=F3|S==S1), P(F=F3|S==S2), P(F=F3|S==S3)
d. Probability of P(F=F4|S==S1), P(F=F4|S==S2), P(F=F4|S==S3)
e. Probability of P(F=F5|S==S1), P(F=F5|S==S2), P(F=F5|S==S3)
</pre>
Ex:

<pre>
[[F1,S1],[F2,S2],[F3,S3],[F1,S2],[F2,S3],[F3,S2],[F2,S1],[F4,S1],[F4,S3],[F5,S1]]

a. P(F=F1|S==S1)=1/4, P(F=F1|S==S2)=1/3, P(F=F1|S==S3)=0/3
b. P(F=F2|S==S1)=1/4, P(F=F2|S==S2)=1/3, P(F=F2|S==S3)=1/3
c. P(F=F3|S==S1)=0/4, P(F=F3|S==S2)=1/3, P(F=F3|S==S3)=1/3
d. P(F=F4|S==S1)=1/4, P(F=F4|S==S2)=0/3, P(F=F4|S==S3)=1/3
e. P(F=F5|S==S1)=1/4, P(F=F5|S==S2)=0/3, P(F=F5|S==S3)=0/3
</pre>




In [73]:
# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input strings



# you can free to change all these codes/structure
def compute_conditional_probabilites(A):
    # your code
    dct = {}
    for i in range(len(A)):
        if A[i][1] in dct:
            dct[A[i][1]] += 1
        else:
            dct[A[i][1]] = 1

    my_dict = dict()
    for i in range(len(A)):
        if A[i][0] +","+ A[i][1] in my_dict:
            my_dict[A[i][0] +","+ A[i][1]] += 1
        else:
            my_dict[A[i][0] +","+ A[i][1]] = 1

    s = set()
    for i in my_dict.items():
        for k in dct.items():      
            if i[0][3:] == k[0]:
                s.add("'"+ i[0] +"'" + " " +str(i[1]/k[1]))
            elif i[0][:-2] + k[0] in my_dict:
                 continue
            else:
                s.add("'"+i[0][:-2] + k[0]+"'" +" " + str(0)) 
    print("lenght of the set", len(s))

    for i in list(s):
        print(i)


A = [['F1','S1'],['F2','S2'],['F3','S3'],['F1','S2'],['F2','S3'],['F3','S2'],['F2','S1'],['F4','S1'],['F4','S3'],['F5','S1']]

compute_conditional_probabilites(A)

lenght of the set 15
'F2,S2' 0.3333333333333333
'F1,S2' 0.3333333333333333
'F3,S2' 0.3333333333333333
'F4,S2' 0
'F5,S1' 0.25
'F1,S1' 0.25
'F2,S1' 0.25
'F4,S1' 0.25
'F2,S3' 0.3333333333333333
'F3,S3' 0.3333333333333333
'F5,S2' 0
'F3,S1' 0
'F1,S3' 0
'F4,S3' 0.3333333333333333
'F5,S3' 0


<h3> Q9: Given two sentances S1, S2</h3>
You will be given two sentances S1, S2 your task is to find 
<pre>
a. Number of common words between S1, S2
b. Words in S1 but not in S2
c. Words in S2 but not in S1
</pre>

Ex: 
<pre>
S1= "the first column F will contain only 5 uniques values"
S2= "the second column S will contain only 3 uniques values"
Output:
a. 7
b. ['first','F','5']
c. ['second','S','3']
</pre>

In [74]:
# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input strings

# you can free to change all these codes/structure
def string_features(S1, S2):
    # your code
    list_S1 = S1.split()
    list_S2 = S2.split()
    count = 0
    list_same_element = []
    for i in list_S1:
        for j in list_S2:
            if i==j:
                count += 1
                list_same_element.append(i)   
            a = count 

    b = set(list_S1) - set(list_same_element) 
    c = set(list_S2) - set(list_same_element)
    return a, b, c

S1= "the first column F will contain only 5 uniques values"
S2= "the second column S will contain only 3 uniques values"
a,b,c = string_features(S1, S2)
print('a.',a)
print('b.',b)
print('c.',c)

a. 7
b. {'F', 'first', '5'}
c. {'second', 'S', '3'}


<h3> Q10: Given two sentances S1, S2</h3>
You will be given a list of lists, each sublist will be of length 2 i.e. [[x,y],[p,q],[l,m]..[r,s]]
consider its like a martrix of n rows and two columns

a. the first column Y will contain interger values <br>
b. the second column $Y_{score}$ will be having float values <br>
Your task is to find the value of $f(Y,Y_{score}) = -1*\frac{1}{n}\Sigma_{for each Y,Y_{score} pair}(Ylog10(Y_{score})+(1-Y)log10(1-Y_{score}))$ here n is the number of rows in the matrix
<pre>
Ex:
[[1, 0.4], [0, 0.5], [0, 0.9], [0, 0.3], [0, 0.6], [1, 0.1], [1, 0.9], [1, 0.8]]
output:
0.4243099
</pre>
$\frac{-1}{8}\cdot((1\cdot log_{10}(0.4)+0\cdot log_{10}(0.6))+(0\cdot log_{10}(0.5)+1\cdot log_{10}(0.5)) + ... + (1\cdot log_{10}(0.8)+0\cdot log_{10}(0.2)) )$

In [75]:
# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input strings


# you can free to change all these codes/structure
def compute_log_loss(A):
    # your code
    loss = 0
    n =len(A)
    for i in A:
        loss += -1/n * (i[0] * math.log10(i[1]) + (1-i[0]) * math.log10(1-i[1]))
    return loss

A = [[1, 0.4], [0, 0.5], [0, 0.9], [0, 0.3], [0, 0.6], [1, 0.1], [1, 0.9], [1, 0.8]]
loss = compute_log_loss(A)
print(loss)

0.42430993457031635
